# 'bundle exec jekyll serve' to test
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: Sarah A. Wu
email: nhcoates@mit.edu
description: >- # this means to ignore newlines until "baseurl:"
    Nicole H Coates
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolehope5.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
socials:
    twitter: nicolehcoates
    github: nicolehope5
    instagram: nicolesundance

collections:
    publications:
        output: true
        permalink: /:collection/:name

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
